### PR TITLE
Add route to fetch all task assigned to a specific user

### LINKED ISSUE #159: Add route to fetch all task  assigned to a specific user
Create a route that handles request to get  all tasks assigned to a user by id

### PR DESCRIPTION
**Pull request by ayodejidaniel**
…this commit close #159" which automatically closes the issue with #159 on merge

### CODE REVIEW

**Comment by ayodejidaniel** [comment]
Created a route handler and controller to fetch all task assigned to a specific user

https://todo.zuri.chat/api/task

link to pull request: #337 

[link to controller](https://github.com/ayodejidaniel/zc_plugin_todo/blob/develop/routes/api.php) : line 75
[link to router](https://github.com/ayodejidaniel/zc_plugin_todo/blob/develop/app/Http/Controllers/TaskController.php) : line 77&92

fill the form to create todo and get request response an error would be returned if some required fields are missing.

**Comment by ayodejidaniel** [comment]
Created a route handler and controller to fetch all task assigned to a specific user

https://todo.zuri.chat/api/task

link to pull request: #337

link to controller : line 75
link to router : line 77&92

fill the form to create todo and get request response an error would be returned if some required fields are missing.

**Comment by ayodejidaniel** [comment]
Created a route handler and controller to fetch all task assigned to a specific user

https://todo.zuri.chat/api/task

link to pull request: #337

link to controller : line 75
link to router : line 77&92

fill the form to create todo and get request response an error would be returned if some required fields are missing.

**Comment by ayodejidaniel** [comment]
Created a route handler and controller to fetch all task assigned to a specific user

https://todo.zuri.chat/api/task

link to pull request: #337

link to controller : line 75
link to router : line 77&92

fill the form to create todo and get request response an error would be returned if some required fields are missing.

**Comment by ayodejidaniel** [comment]
Created a route handler and controller to fetch all task assigned to a specific user

https://todo.zuri.chat/api/task

link to pull request: #337

[link to controller](https://github.com/ayodejidaniel/zc_plugin_todo/blob/develop/app/Http/Controllers/TaskController.php) : line 75
[link to router](https://github.com/ayodejidaniel/zc_plugin_todo/blob/develop/routes/api.php) : line 77&92

**Comment by ayodejidaniel** [comment]
reopen for merge

**Comment by kayleb01** [comment]
First of all I don't understand what you are doing here, you are just getting the tasks for the workspace and then what?
How does this relate to the user?
And there's conflict

**Pull request closed without merging**
