### PR TITLE
Add route to fetch all task assigned to a specific user

### PR DESCRIPTION
**Pull request by ayodejidaniel**
compare branch

### CODE REVIEW

**Review by kayleb01 — COMMENTED** [review]
@ayodejidaniel  Please what issue is this??

**Comment by ayodejidaniel** [comment]
Created a route handler and controller to fetch all task assigned to a specific user

https://todo.zuri.chat/api/task/assign/1

link to pull request: #410 

[link to controller](https://github.com/ayodejidaniel/zc_plugin_todo/blob/zurilocal/app/Http/Controllers/AssignTaskUserController.php) : line 38 to 51
[link to router](https://github.com/ayodejidaniel/zc_plugin_todo/blob/zurilocal/routes/api.php) : line 91

**Comment by ayodejidaniel** [comment]
@kayleb01 Add route to fetch all task assigned to a specific user

**Review by kayleb01 — COMMENTED** [review]
Please why does your PR having changes to the .htaccess file?

**Comment by kayleb01** [comment]
Is it that you added a .htaccess file??

**Comment by ayodejidaniel** [comment]
ooh sorry I thought I added it to .gitignore

**Comment by ayodejidaniel** [comment]
…this commit close #159" which automatically closes the issue with #159 on merge

**Pull request merged**
